# Generated by Django 4.0.2 on 2022-02-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(db_column='Document Name', max_length=100)),
                ('confidence', models.IntegerField(db_column='Confidence Score')),
                ('ddt', models.BooleanField(db_column='DDT Classification?')),
                ('keywords', models.TextField(db_column='Keywords Identified')),
                ('filepath', models.FileField(db_column='Document', null=True, upload_to='files/', verbose_name='')),
            ],
            options={
                'db_table': 'results',
            },
        ),
    ]
